version: "3.3"
services:
  products-web:
    build: .
    container_name: products-web
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
